a=int(input("Enter number 1 : "))
b=int(input("Enter number 2 : "))
print("addition=",a+b)
print("substraction=",a-b)
print("multiplication=",a*b)
print("division=",a/b)
print("power=",a**b)
print("floor division=",a//b)
print("modulus=",a%b)

